In [2]:
import numpy as np
import time

size = 1_000_000_0
list1=list(range(size))
list2=list(range(size))

st = time.time()
result = [x+y for x,y in zip(list1,list2)]
end = time.time()

print("Time Taken: ",end-st)

Time Taken:  0.6825757026672363


In [3]:
size = 1_000_000_0
arr1 = np.array(list1)
arr2 = np.array(list2)

st = time.time()
result = arr1 + arr2
end = time.time()

print("Time Taken: ",end-st)

Time Taken:  0.12118053436279297


In [4]:
l1 = [1,2,3,4]
l2 = [5,6,7,8]
arr=list(zip(l1,l2))
print(arr)

[(1, 5), (2, 6), (3, 7), (4, 8)]


In [5]:
# 1-D array
arr1=np.array([1,2,3,4])
print("arr1:",arr1)

print("Type:",type(arr1))
print("Shape:",arr1.shape)

# 2-D array
arr2=np.array([[1,2,3],[4,5,6]])
print("arr2:",arr2)


print("Type:",type(arr2))
print("Shape:",arr2.shape)

arr1: [1 2 3 4]
Type: <class 'numpy.ndarray'>
Shape: (4,)
arr2: [[1 2 3]
 [4 5 6]]
Type: <class 'numpy.ndarray'>
Shape: (2, 3)


In [6]:
# Checking memory consumption

import sys

list_data = list(range(1000))
numpy_data = np.array(list_data)

print("Python list size: ", sys.getsizeof(list_data)*len(list_data),"bytes")
print("Numpy array size: ", numpy_data.nbytes, "bytes")

Python list size:  8056000 bytes
Numpy array size:  4000 bytes


In [7]:
# Vectorization in numpy arrays
list1 = list(range(10000000))

st1 = time.time()
list_square = [x**2 for x in list1]
end1 = time.time()
print("Time taken by list: ",end1-st1)


arr1 = np.array(list1)
st2 = time.time()
arr_square = arr1**2
end2 = time.time()
print("Time taken by array: ",end2-st2)

Time taken by list:  0.7789933681488037
Time taken by array:  0.0214235782623291


In [8]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.full((4,6),8)

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [11]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
np.arange(0,101,5)

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [13]:
np.linspace(1,100,5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [14]:
# array properties
arr = np.array([[1,2,3],[4,5,6]])

print("Shape:",arr.shape)
print("Size:",arr.size)
print("Dimension:",arr.ndim)
print("Data Type:",arr.dtype)

Shape: (2, 3)
Size: 6
Dimension: 2
Data Type: int32


In [15]:
# defining array type explicitly
arr = np.array([1,2,3],dtype=np.float32)
print(arr.dtype)


# converting float array to int
arr_int = arr.astype(np.int32)
print(arr_int)

float32
[1 2 3]


In [16]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr.shape

(3, 4)

In [17]:
arr1 = arr.reshape((4,3))
print("arr1:",arr1)
arr1.shape

arr1: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


(4, 3)

In [18]:
arr2 = arr.reshape((2,6))
print("arr2:",arr2)
arr2.shape

arr2: [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


(2, 6)

In [19]:
arr3 = arr.reshape((6,2))
print("arr3:",arr3)
arr3.shape

arr3: [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


(6, 2)

In [20]:
arr4 = arr.flatten()
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [21]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [22]:
flat = arr.flatten()
print(flat)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [23]:
flat[0]

1

In [24]:
b = flat[2:5]
b

array([3, 4, 5])

In [25]:
b[2]=444
b 

array([  3,   4, 444])

In [26]:
flat

array([  1,   2,   3,   4, 444,   6,   7,   8,   9,  10,  11,  12])

In [27]:
# Fancy Indexing

arr = np.array([1,2,3,4,5,6,7,8,9])
idx = [1,5,8]
arr[idx]

array([2, 6, 9])

In [28]:
# Boolean Masking
arr = np.array([10,20,30,40,50])
mask = arr>25
print(arr[mask])

[30 40 50]


In [29]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)

(3, 3)


In [30]:
arr = np.array([1.1,2.2,3.3])
int_arr = arr.astype(np.int32)
print(int_arr)

[1 2 3]


In [31]:
arr = np.array([1,2,3,4,5,6])
idx = [1,3,5]
print(arr[idx])

[2 4 6]


In [32]:
arr = np.array([1,2,3,4,5,6,7,8,9])
ans = arr.reshape(3,3)
print(ans)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
arr = np.array([12,35,14,78,96,10,25,68,14,36,57])
mask1 = arr>50
mask2 = arr<=50
print(arr[mask1])
print(arr[mask2])

[78 96 68 57]
[12 35 14 10 25 14 36]


In [34]:
arr = np.array([1,2,3,4,5,6])
idx = arr%2==0
print(arr[idx])

[2 4 6]


Multidimensional indexing and Axes

In [35]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
arr[0]

array([1, 2, 3])

In [36]:
np.sum(arr,axis=0)  # operation moves down the columns 

array([12, 15, 18])

In [37]:
np.sum(arr,axis=1)  # operation moves across the rows

array([ 6, 15, 24])

In [38]:
arr[0][1]   # Normal Indexing

2

In [39]:
arr[0,1]   # Numpy Indexing

2

In [40]:
arr[0:2 , 1:3]  # arr[rows,columns]

array([[2, 3],
       [5, 6]])

In [41]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])

# Output of arr3D.shape is → (depth, rows, columns)
print(arr3D.shape)  # Output: (2, 2, 3) 

(2, 2, 3)


In [42]:
arr3D[0,1,2]

6

In [43]:
arr3D[1,0,1]

8

In [44]:
arr3D[0:1,1:2,1:3]

array([[[5, 6]]])

In [45]:
arr3D[:,0,:]

array([[1, 2, 3],
       [7, 8, 9]])

Numpy Datatypes

In [46]:
# astype   typecast to different dtype
# nbytes   to check memory usage



Loops , Vectorization , Broadcasting

In [48]:
arr = np.array([3,5,9,8,6,10,25,15])
result = []

# Loop
for i in arr:
    i=i**2
    result.append(i)
    
 
print(result)

[9, 25, 81, 64, 36, 100, 625, 225]


In [ ]:
# using vectorization , operation is applied to array without generating any copies
new_arr = arr**2

print(new_arr)


[  9  25  81  64  36 100 625 225]


In [52]:
# Broadcasting can be used to perform operations on arrays of differen shapes

arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([7,8,9])

new_arr = arr1 + arr2
print(new_arr)

[[ 8 10 12]
 [11 13 15]]


Numpy Built-in mathematical functions

In [53]:
arr = np.array([20,35,15,87,63,19,28,34,64,52])

In [60]:
np.mean(arr)

41.7

In [61]:
np.std(arr)

22.58340098390851

In [62]:
np.var(arr)

510.00999999999993

In [63]:
np.min(arr)

15

In [64]:
np.max(arr)

87

In [65]:
np.sum(arr)

417

In [66]:
np.prod(arr)

345972736

In [68]:
np.median(arr)

34.5

In [70]:
np.percentile(arr , 90)

66.3

In [71]:
np.argmin(arr)  #return index of min

2

In [73]:
np.argmax(arr)  #index of max

3

In [74]:
np.unique(arr)

array([15, 19, 20, 28, 34, 35, 52, 63, 64, 87])

In [75]:
np.diff(arr)

array([ 15, -20,  72, -24, -44,   9,   6,  30, -12])

In [76]:
np.cumsum(arr)  #cumulative sum

array([ 20,  55,  70, 157, 220, 239, 267, 301, 365, 417])

In [77]:
np.log(arr)

array([2.99573227, 3.55534806, 2.7080502 , 4.46590812, 4.14313473,
       2.94443898, 3.33220451, 3.52636052, 4.15888308, 3.95124372])

In [78]:
np.exp(arr)

array([4.85165195e+08, 1.58601345e+15, 3.26901737e+06, 6.07603023e+37,
       2.29378316e+27, 1.78482301e+08, 1.44625706e+12, 5.83461743e+14,
       6.23514908e+27, 3.83100800e+22])

In [83]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])